# Build
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Runtime
FROM node:20-alpine AS runtime
WORKDIR /app

COPY --from=build /app/.next .next
COPY --from=build /app/public ./public
COPY --from=build /app/package*.json ./
COPY --from=build /app/next.config.ts next.config.ts

RUN npm ci --omit=dev

EXPOSE 11769

CMD ["npm", "run", "start"]